name: Request Worklog Report
run-name: ${{ github.actor }} has received a request to populate a worklog report
on:
  workflow_dispatch:
  issues:
    types:
        - opened
        - closed
        - reopened
        - labeled
        - unlabeled

jobs:
  receive-request-workflow-report:
    runs-on: self-hosted
    steps:
      - run: echo "Connected"
      - name: Parse inputs
        env:
          body : ${{ github.event.issue.body}}
        run: |
          echo $body > /tmp/.action.md
          cat /tmp/.action.md
