name: Request Worklog Report
run-name: ${{ github.actor }} has received a request to populate a worklog report
on:
  workflow_dispatch:
  issues:
    types:
        - opened

jobs:
  receive-request-workflow-report:
    runs-on: self-hosted
    steps:
      - run: echo "Connected"
      - name: Parse inputs
        env:
          jql : ${{ github.event.issue.body.jql }}
          email_to: ${{ github.event.issue.body.email_to }}
        run: |
          printf "JQL=%s\n" "${jql}"
          printf "EMAIL_TO=%s\n" "${email_to}"
