name: Request Worklog Report
run-name: ${{ github.actor }} has received a request to populate a worklog report
on:
  workflow_dispatch:
  issues:
    types:
        - opened
        - closed
        - reopened
        - labeled
        - unlabeled

jobs:
  receive-request-workflow-report:
    runs-on: self-hosted
    steps:
      - run: echo "Connected"
      - name: Issue Forms Body Parser
        id: parse
        uses: zentered/issue-forms-body-parser@v1.4.3
      - run: echo "${{ JSON.stringify(steps.parse.outputs.data) }}"
      - name: Parse inputs
        env:
          body : ${{ github.event.issue.body}}
          jql : ${{ github.event.issue.body.jql }}
          email_to: ${{ github.event.issue.body.email_to }}
        run: |
          echo "BODY=$body"
          echo "JQL=$jql"
          echo "EMAIL_TO=$email_to"
